version: '3'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
  backend:
    image: backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=user1
      - DB_PASSWORD=password1
      - DB_HOST=db
    depends_on:
      - db
  redis:
    image: redis
    expose:
      - 6379

  db:
    image: postgres
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password1
    container_name: db
    expose: 
      - 8000